set nocompatible                      " not compatible with vi

source ~/.vim/plugins.vim             " Load plugins with vimplug

" General settings
set autoread                          " detect when a file changed
set encoding=utf-8
set fileencodings=utf-8

syntax on                             " enable syntax
set ttyfast                           " redraw fast
set lazyredraw                        " speedup vim
set updatetime=250
set timeoutlen=200                    " make vim more snappy
set number                            " enable line numbers
set rnu                               " relative numbers
set nobackup                          " no backup files and so on
set nowb
set noswapfile
set backspace=indent,eol,start        " make backspace work as expected
set list
set listchars=tab:→\ ,trail:▶         " Visualize trailing elements
set wildmenu                          " enhanced command line completion
set showcmd                           " show command
set ruler                             " show cursor position
set winwidth=80                       " minimal window width of 80

" Text format
set tabstop=2
set shiftwidth=2
set expandtab                         " insert spaces instead of tab
set softtabstop=2
set nowrap                            " don't break text

" Searching
set ignorecase                        " ignore cases by default
set smartcase
set incsearch

" Bells
set noerrorbells                      " disable bells
set visualbell

" Navigation
set splitbelow                        " more natural splitting
set splitright

" Colors & Colorscheme
set colorcolumn=80                    " visualize max width
set t_Co=256
set background=dark
set term=screen-256color
colorscheme solarized

" Keybindings
let mapleader=','

inoremap jk <esc>                         " remap esc
nmap <silent> <leader>v :vsplit<cr>       " split vertical
nmap <silent> <leader>s :split<cr>        " split horizontal
nmap <silent> <leader>e :Explore<cr>      " Explore
nmap <silent> <leader><Tab> :tabnew<cr>   " New Tab
nmap <silent> <Tab> :tabn<cr>             " Next tab
nmap <silent> <S-Tab> :tabp<cr>           " Previous tab
map <c-j> <c-w><down>                     " Easy navigation
map <c-k> <c-w><up>
map <c-h> <c-w><left>
map <c-l> <c-w><right>
noremap <Leader>y "+y
noremap <Leader>p "+p

" Plugin Settings

" FZF <3
let $FZF_DEFAULT_COMMAND = 'ag -U -l -g ""'
let g:fzf_layout = { 'down': '~25%' } " FZF layout when in tmux session
nmap <silent> <leader>f :Files<cr>
nmap <silent> <leader>c :Commits<cr>
nmap <silent> <leader>b :Buffers<cr>

let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" Ack
if executable('ag')
  let g:ackprg = 'ag --nogroup --nocolor --column -U'
end

nmap <leader>a :Ack!<Space>

" Vimux
nmap <leader>q :VimuxPromptCommand<cr>
nmap <leader>w :VimuxRunLastCommand<cr>
