set nocompatible                      " not compatible with vi

source ~/.vim/plugins.vim             " Load plugins with vimplug

" General settings
set autoread                          " detect when a file changed
set encoding=utf-8
set fileencodings=utf-8

syntax on                             " enable syntax
set ttyfast                           " redraw fast
set lazyredraw                        " speedup vim
set number                            " enable line numbers
set rnu                               " relative numbers
set nobackup                          " no backup files and so on
set nowb                              " no backup files and so on
set swapfile                          " no backup files and so on
set backspace=indent,eol,start        " make backspace work as expected
set list
set listchars=tab:→\ ,trail:▶         " Visualize trailing elements

" Text format
set tabstop=2
set shiftwidth=2
set expandtab                         " insert spaces instead of tab
set softtabstop=2
set nowrap                            " don't break text

" Searching
set ignorecase                        " ignore cases by default
set smartcase
set incsearch

" Bells
set noerrorbells                      " disable bells
set visualbell

" Colors & Colorscheme
set colorcolumn=80                    " visualize max width
set t_Co=256
set background=dark
let g:gruvbox_contrast_dark='medium'
let g:gruvbox_contrast_dark='medium'
colorscheme gruvbox                   " best colorscheme in the world

" Keybindings
let mapleader=','

inoremap jk <esc>                     " remap esc
nmap <leader>, :w<cr>                 " shortcut for saving


" Plugin Settings

" FZF <3
let g:fzf_layout = { 'down': '~25%' } " FZF layout when in tmux session
nmap <silent> <leader>f :Files<cr>
nmap <silent> <leader>c :Commits<cr>
nmap <silent> <leader>b :Buffers<cr>
