# ignore duplicate entries and the ones starting with space
HISTCONTROL=ignoreboth
# append to the history file
shopt -s histappend
# history size
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary
shopt -s checkwinsize

# source aliases
if [[ -f ~/.bash_aliases ]]; then
  source ~/.bash_aliases
fi

# add ~/bin to PATH
if [[ -d ~/bin ]]; then
  export PATH=~/bin:$PATH
fi

# source a localrc if exists
if [[ -a ~/.localrc ]]; then
  source ~/.localrc
fi

# VIM as editor
export EDITOR='vim'

# Get git branch for prompt
parse_git_branch() {
 git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

# Bash prompt
PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;31m\] \$(parse_git_branch)\[\033[00m\] \n$ "

# Setup rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
# Load rbenv automatically
eval "$(rbenv init -)"

# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# More intelligent bash history browsing
if [[ $- == *i* ]]
then
    bind '"\e[A": history-search-backward'
    bind '"\e[B": history-search-forward'
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Usage: reminder 10m tea
function reminder()
{
  (sleep $1; gxmessage -nearmouse ${2:-Reminder}) &
}

# Simplify scanning
function scan()
{
  scanimage --device "brother4:net1;dev0" --format=png > $1.png
}

# Shortcut to set external monitor
function set_external_monitor()
{
  xrandr --output eDP1 --auto --output DP1 --auto --${1:-left}-of eDP1 --primary
}

function disable_external_monitor()
{
  xrandr --output eDP1 --auto --output DP1 --off
}

# tmuxinator
source ~/bin/tmuxinator.bash
